language: python
python: '2.7'
sudo: false
cache:
  pip: true
  directories:
    - node_modules
    - components
    - eggs
addons:
  firefox: 45.8.0esr
before_install:
  - cp test-$PLONE_VERSION.x.cfg buildout.cfg
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install zc.buildout
  - buildout -N annotate
  - buildout -N
  - mkdir -p parts/test/_screenshots
  - make install
  - node_modules/bower/bin/bower install
  - make clean all mode=release
script:
  - bin/test $TEST_OPTIONS
  - bin/pybot -d parts/test docs
after_script:
  - bin/sphinx-build docs html
  - bundle install
  - bundle exec travis-artifacts upload --path html
  - bundle exec travis-artifacts upload --path parts/test
  - bundle exec travis-artifacts upload --target-path latest --path html
  - bundle exec travis-artifacts upload --target-path latest --path parts/test
  - 'echo "Sphinx: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/"'
  - 'echo "Robot: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/report.html"'
env:
  matrix:
    - PLONE_VERSION=4.3
    - PLONE_VERSION=5.0
  global:
    - ARTIFACTS_S3_BUCKET=plone-app-mosaic
    - secure: F9djE/1a4VvCidHCnWeF7qkwsUhVLZELv/ttSC1UamsbCCzIa0shUheF4MfAZBRcwtVVAlrid4VRnuYnxyDciy2jrL/qayLfze2ZKcZTfYKsNIrQzyZ4SUVZRB9ZSA6yUK3v+/GIie95as8MKM/UxRtn2RWw4doWGyKv8XBOL4U=
    - secure: buYYreaObmTNEuVTibj/kIyFnIoHCZdezeA8P0HwGHrTbIAwArBFfhG5PC1grT8MayN3f4sfY80d8sRhRATTPNX1smjjBfyni/Zon8OTpr6mGaGsHOg+HHHqocy3hZPlgg1yYLpUCfKCOc8pnq09lF06JwPxsIXAiV+oRHR446E=
irc:
  channels:
    - irc.freenode.org#plone-testing
  template:
    - '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
    - 'Change: %{compare_url}'
    - 'Details: %{build_url}'
    - 'Artifacts: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/latest/'
